### ISSUE TITLE
Rats, error with latest commits

### ISSUE THREAD

**Issue by tildebyte** [nhanb/pytaku-old-gae#8]
Oh good god, nvm. I'm an idiot, and forgot that there are extra steps to follow before deploying in own cloud.

I just did a ff to master and re-deployed. Now I'm seeing

```python
Traceback (most recent call last):
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler handler, path, err = LoadObject(self._handler)
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject obj = __import__(path[0])
File "/base/data/home/apps/s~pytaku-1155/20170127t121022.398770812304092543/main.py", line 2, in <module> from pytaku.api.api import RegisterHandler, LoginHandler, SeriesHandler,\
File "/base/data/home/apps/s~pytaku-1155/20170127t121022.398770812304092543/pytaku/api/api.py", line 8, in <module> from pytaku.models import User, createUser, Chapter, Series, ChapterProgress
File "/base/data/home/apps/s~pytaku-1155/20170127t121022.398770812304092543/pytaku/models.py", line 2, in <module> from passlib.hash import pbkdf2_sha512
ImportError: No module named passlib.hash
```

in the GAE request_log.

I don't know what else you might need, but let me know (it's probably something reeely obvious).

[edit edit] Grr, wrong. The previously working version is fine.
[edit] Now *all* versions (including the one which used to work) are throwing this... :(

Also, maybe unrelated, maybe not: `gcloud deploy` now complains about the `application` and `version` tags in `app.yaml`.

**Comment by nhanb** [comment]
>Also, maybe unrelated, maybe not: gcloud deploy now complains about the application and version tags in app.yaml.

I'm still using the old [Google App Engine SDK](https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.50.zip), not the new [gcloud](https://cloud.google.com/sdk/docs/). Switching back to GAE might get rid of those complaints you're getting.

**Comment by tildebyte** [comment]
Understood, although it *seems* to work fine without. It's also nice that the Cloud API auto-generates a version tag (from datetime); I don't have enough imagination to constantly come up with new tags :D
